# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

intervals_lvx <- function(lvx) {
    .Call(`_lazyNumbers_intervals_lvx`, lvx)
}

nv2lvx <- function(nv) {
    .Call(`_lazyNumbers_nv2lvx`, nv)
}

nm2lmx <- function(nm) {
    .Call(`_lazyNumbers_nm2lmx`, nm)
}

lvx2nv <- function(lvx) {
    .Call(`_lazyNumbers_lvx2nv`, lvx)
}

lmx2nm <- function(lmx) {
    .Call(`_lazyNumbers_lmx2nm`, lmx)
}

minus_lvx <- function(lvx) {
    .Call(`_lazyNumbers_minus_lvx`, lvx)
}

minus_lmx <- function(lmx) {
    .Call(`_lazyNumbers_minus_lmx`, lmx)
}

lvx_plus_lvx <- function(lvx1, lvx2) {
    .Call(`_lazyNumbers_lvx_plus_lvx`, lvx1, lvx2)
}

lmx_plus_lmx <- function(lmx1, lmx2) {
    .Call(`_lazyNumbers_lmx_plus_lmx`, lmx1, lmx2)
}

lvx_minus_lvx <- function(lvx1, lvx2) {
    .Call(`_lazyNumbers_lvx_minus_lvx`, lvx1, lvx2)
}

lmx_minus_lmx <- function(lmx1, lmx2) {
    .Call(`_lazyNumbers_lmx_minus_lmx`, lmx1, lmx2)
}

lvx_times_lvx <- function(lvx1, lvx2) {
    .Call(`_lazyNumbers_lvx_times_lvx`, lvx1, lvx2)
}

lmx_cwtimes_lmx <- function(lmx1, lmx2) {
    .Call(`_lazyNumbers_lmx_cwtimes_lmx`, lmx1, lmx2)
}

lmx_times_lmx <- function(lmx1, lmx2) {
    .Call(`_lazyNumbers_lmx_times_lmx`, lmx1, lmx2)
}

lvx_dividedby_lvx <- function(lvx1, lvx2) {
    .Call(`_lazyNumbers_lvx_dividedby_lvx`, lvx1, lvx2)
}

lmx_dividedby_lmx <- function(lmx1, lmx2) {
    .Call(`_lazyNumbers_lmx_dividedby_lmx`, lmx1, lmx2)
}

lazySum <- function(lvx) {
    .Call(`_lazyNumbers_lazySum`, lvx)
}

lazyProd <- function(lvx) {
    .Call(`_lazyNumbers_lazyProd`, lvx)
}

lazyCumsum <- function(lvx) {
    .Call(`_lazyNumbers_lazyCumsum`, lvx)
}

lazyCumprod <- function(lvx) {
    .Call(`_lazyNumbers_lazyCumprod`, lvx)
}

lazyMax <- function(lvx) {
    .Call(`_lazyNumbers_lazyMax`, lvx)
}

lazyMin <- function(lvx) {
    .Call(`_lazyNumbers_lazyMin`, lvx)
}

lazyRange <- function(lvx) {
    .Call(`_lazyNumbers_lazyRange`, lvx)
}

