# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lazyNA <- function() {
    .Call(`_lazyNumbers_lazyNA`)
}

isLazyNA <- function(lvx) {
    .Call(`_lazyNumbers_isLazyNA`, lvx)
}

MisLazyNA <- function(lmx) {
    .Call(`_lazyNumbers_MisLazyNA`, lmx)
}

lazyExact <- function(lvx) {
    invisible(.Call(`_lazyNumbers_lazyExact`, lvx))
}

MlazyExact <- function(lmx) {
    invisible(.Call(`_lazyNumbers_MlazyExact`, lmx))
}

intervals_lvx <- function(lvx) {
    .Call(`_lazyNumbers_intervals_lvx`, lvx)
}

intervals_lmx <- function(lmx) {
    .Call(`_lazyNumbers_intervals_lmx`, lmx)
}

nv2lvx <- function(nv) {
    .Call(`_lazyNumbers_nv2lvx`, nv)
}

nm2lmx <- function(nm) {
    .Call(`_lazyNumbers_nm2lmx`, nm)
}

lvx2nv <- function(lvx) {
    .Call(`_lazyNumbers_lvx2nv`, lvx)
}

lmx2nm <- function(lmx) {
    .Call(`_lazyNumbers_lmx2nm`, lmx)
}

minus_lvx <- function(lvx) {
    .Call(`_lazyNumbers_minus_lvx`, lvx)
}

minus_lmx <- function(lmx) {
    .Call(`_lazyNumbers_minus_lmx`, lmx)
}

lvx_plus_lvx <- function(lvx1, lvx2) {
    .Call(`_lazyNumbers_lvx_plus_lvx`, lvx1, lvx2)
}

lmx_plus_lmx <- function(lmx1, lmx2) {
    .Call(`_lazyNumbers_lmx_plus_lmx`, lmx1, lmx2)
}

lvx_minus_lvx <- function(lvx1, lvx2) {
    .Call(`_lazyNumbers_lvx_minus_lvx`, lvx1, lvx2)
}

lmx_minus_lmx <- function(lmx1, lmx2) {
    .Call(`_lazyNumbers_lmx_minus_lmx`, lmx1, lmx2)
}

lvx_times_lvx <- function(lvx1, lvx2) {
    .Call(`_lazyNumbers_lvx_times_lvx`, lvx1, lvx2)
}

lmx_cwtimes_lmx <- function(lmx1, lmx2) {
    .Call(`_lazyNumbers_lmx_cwtimes_lmx`, lmx1, lmx2)
}

lmx_times_lmx <- function(lmx1, lmx2) {
    .Call(`_lazyNumbers_lmx_times_lmx`, lmx1, lmx2)
}

lvx_dividedby_lvx <- function(lvx1, lvx2) {
    .Call(`_lazyNumbers_lvx_dividedby_lvx`, lvx1, lvx2)
}

lmx_dividedby_lmx <- function(lmx1, lmx2) {
    .Call(`_lazyNumbers_lmx_dividedby_lmx`, lmx1, lmx2)
}

lazySum <- function(lvx) {
    .Call(`_lazyNumbers_lazySum`, lvx)
}

lazyProd <- function(lvx) {
    .Call(`_lazyNumbers_lazyProd`, lvx)
}

lazyCumsum <- function(lvx) {
    .Call(`_lazyNumbers_lazyCumsum`, lvx)
}

lazyCumprod <- function(lvx) {
    .Call(`_lazyNumbers_lazyCumprod`, lvx)
}

lazyConcat <- function(lvx1, lvx2) {
    .Call(`_lazyNumbers_lazyConcat`, lvx1, lvx2)
}

lazyMax <- function(lvx) {
    .Call(`_lazyNumbers_lazyMax`, lvx)
}

lazyMin <- function(lvx) {
    .Call(`_lazyNumbers_lazyMin`, lvx)
}

lazyRange <- function(lvx) {
    .Call(`_lazyNumbers_lazyRange`, lvx)
}

MlazyProd <- function(lmx) {
    .Call(`_lazyNumbers_MlazyProd`, lmx)
}

MlazySum <- function(lmx) {
    .Call(`_lazyNumbers_MlazySum`, lmx)
}

MlazyMax <- function(lmx) {
    .Call(`_lazyNumbers_MlazyMax`, lmx)
}

MlazyMin <- function(lmx) {
    .Call(`_lazyNumbers_MlazyMin`, lmx)
}

MlazyRange <- function(lmx) {
    .Call(`_lazyNumbers_MlazyRange`, lmx)
}

lazyPower <- function(lvx, alpha) {
    .Call(`_lazyNumbers_lazyPower`, lvx, alpha)
}

MlazyPower <- function(lmx, alpha) {
    .Call(`_lazyNumbers_MlazyPower`, lmx, alpha)
}

lazyAbs <- function(lvx) {
    .Call(`_lazyNumbers_lazyAbs`, lvx)
}

MlazyAbs <- function(lmx) {
    .Call(`_lazyNumbers_MlazyAbs`, lmx)
}

lazyExtract <- function(lvx, indices) {
    .Call(`_lazyNumbers_lazyExtract`, lvx, indices)
}

MlazyExtract <- function(lmx, indices, m, n) {
    .Call(`_lazyNumbers_MlazyExtract`, lmx, indices, m, n)
}

lazyReplace <- function(lvx1, indices, lvx2) {
    .Call(`_lazyNumbers_lazyReplace`, lvx1, indices, lvx2)
}

lazyColumnMatrix <- function(lvx) {
    .Call(`_lazyNumbers_lazyColumnMatrix`, lvx)
}

lazyRowMatrix <- function(lvx) {
    .Call(`_lazyNumbers_lazyRowMatrix`, lvx)
}

lazyRbind <- function(lmx1, lmx2) {
    .Call(`_lazyNumbers_lazyRbind`, lmx1, lmx2)
}

lazyCbind <- function(lmx1, lmx2) {
    .Call(`_lazyNumbers_lazyCbind`, lmx1, lmx2)
}

lazyDeterminant <- function(lmx) {
    .Call(`_lazyNumbers_lazyDeterminant`, lmx)
}

lazyInverse <- function(lmx) {
    .Call(`_lazyNumbers_lazyInverse`, lmx)
}

lazyTranspose <- function(lmx) {
    .Call(`_lazyNumbers_lazyTranspose`, lmx)
}

lazyFlatten <- function(lmx) {
    .Call(`_lazyNumbers_lazyFlatten`, lmx)
}

lazyCompare <- function(lvx1, lvx2, r) {
    .Call(`_lazyNumbers_lazyCompare`, lvx1, lvx2, r)
}

lazyDiagonal <- function(lmx) {
    .Call(`_lazyNumbers_lazyDiagonal`, lmx)
}

lazyReplaceDiagonal <- function(lmx, lvx) {
    .Call(`_lazyNumbers_lazyReplaceDiagonal`, lmx, lvx)
}

