# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nv2lvx <- function(nv) {
    .Call(`_lazyNumbers_nv2lvx`, nv)
}

lvx2nv <- function(lvx) {
    .Call(`_lazyNumbers_lvx2nv`, lvx)
}

minus_lvx <- function(lvx) {
    .Call(`_lazyNumbers_minus_lvx`, lvx)
}

lvx_plus_lvx <- function(lvx1, lvx2) {
    .Call(`_lazyNumbers_lvx_plus_lvx`, lvx1, lvx2)
}

lvx_minus_lvx <- function(lvx1, lvx2) {
    .Call(`_lazyNumbers_lvx_minus_lvx`, lvx1, lvx2)
}

lvx_times_lvx <- function(lvx1, lvx2) {
    .Call(`_lazyNumbers_lvx_times_lvx`, lvx1, lvx2)
}

lvx_dividedby_lvx <- function(lvx1, lvx2) {
    .Call(`_lazyNumbers_lvx_dividedby_lvx`, lvx1, lvx2)
}

lazySum <- function(lvx) {
    .Call(`_lazyNumbers_lazySum`, lvx)
}

lazyProd <- function(lvx) {
    .Call(`_lazyNumbers_lazyProd`, lvx)
}

lazyCumsum <- function(lvx) {
    .Call(`_lazyNumbers_lazyCumsum`, lvx)
}

lazyCumprod <- function(lvx) {
    .Call(`_lazyNumbers_lazyCumprod`, lvx)
}

lazyMax <- function(lvx) {
    .Call(`_lazyNumbers_lazyMax`, lvx)
}

lazyMin <- function(lvx) {
    .Call(`_lazyNumbers_lazyMin`, lvx)
}

lazyRange <- function(lvx) {
    .Call(`_lazyNumbers_lazyRange`, lvx)
}

